const SOURCE_LINKS = [
  {
    title: "西安市2025年高中阶段学校招生录取工作方案",
    url: "https://qidian.sxtvs.com/timing/share/content/10620669",
    note: "城六区志愿批次、定向志愿、平行志愿规则"
  },
  {
    title: "2025年城六区普通高中录取控制线",
    url: "https://www.sxks114.com/h-nd-18538.html",
    note: "2025年城六区普高控制线611.0分"
  },
  {
    title: "2025年西安中考各中学录取分数线汇总",
    url: "https://www.xinshinet.com/lz/zkfsx/13605.html",
    note: "2025年学校录取参考线"
  },
  {
    title: "2024年西安中考各高中录取分数线汇总",
    url: "https://www.xinshinet.com/lz/zkfsx/6140.html",
    note: "2024年学校录取参考线"
  },
  {
    title: "2023年西安中考120所高中学校录取分数线一览表",
    url: "https://www.xijingtongcheng.com/xian-education/1370.html",
    note: "2023年学校录取参考线"
  },
  {
    title: "2026年西安市中考计分科目",
    url: "https://xa.bendibao.com/edu/202633/148243.shtm",
    note: "2026年计分科目7科，满分640分"
  }
];

const CONTROL_LINES = {
  2023: { line: 539, max: 700, label: "2023 城六区普高线" },
  2024: { line: 501, max: 700, label: "2024 城六区普高线" },
  2025: { line: 611, max: 820, label: "2025 城六区普高线" }
};

const TARGET_YEAR_PRESETS = {
  2026: { label: "2026预测", max: 640, control: 480, locked: false },
  2025: { label: "2025复盘", max: 820, control: 611, locked: true },
  2024: { label: "2024复盘", max: 700, control: 501, locked: true },
  2023: { label: "2023复盘", max: 700, control: 539, locked: true }
};

const RANK_REFERENCE_DATA = {
  sourceTitle: "2025年西安市城六区中考一分一段表",
  sourceFile: "20-25西安中考一分一段表.pdf",
  year: 2025,
  max: 820,
  control: 611,
  totalRankBase: 49900,
  points: [
    { score: 802, rank: 1, percentile: 0.001 },
    { score: 801, rank: 70, percentile: 0.0014 },
    { score: 800, rank: 110, percentile: 0.0022 },
    { score: 795, rank: 300, percentile: 0.006 },
    { score: 790, rank: 650, percentile: 0.0131 },
    { score: 785, rank: 1260, percentile: 0.0253 },
    { score: 780, rank: 2115, percentile: 0.0425 },
    { score: 775, rank: 3300, percentile: 0.0663 },
    { score: 770, rank: 4572, percentile: 0.0918 },
    { score: 765, rank: 6017, percentile: 0.1208 },
    { score: 760, rank: 7610, percentile: 0.1528 },
    { score: 755, rank: 9235, percentile: 0.1854 },
    { score: 750, rank: 10929, percentile: 0.2195 },
    { score: 745, rank: 12654, percentile: 0.2541 },
    { score: 740, rank: 14379, percentile: 0.2887 },
    { score: 735, rank: 15959, percentile: 0.3205 },
    { score: 730, rank: 17539, percentile: 0.3522 },
    { score: 725, rank: 19119, percentile: 0.3839 },
    { score: 720, rank: 20699, percentile: 0.4156 },
    { score: 715, rank: 22300, percentile: 0.4478 },
    { score: 710, rank: 24300, percentile: 0.488 },
    { score: 705, rank: 25439, percentile: 0.5108 },
    { score: 700, rank: 27260, percentile: 0.5474 },
    { score: 695, rank: 28555, percentile: 0.5734 },
    { score: 690, rank: 29830, percentile: 0.599 },
    { score: 685, rank: 31105, percentile: 0.6246 },
    { score: 680, rank: 32380, percentile: 0.6502 },
    { score: 675, rank: 33655, percentile: 0.6758 },
    { score: 670, rank: 34930, percentile: 0.7014 },
    { score: 665, rank: 36205, percentile: 0.727 },
    { score: 660, rank: 37480, percentile: 0.7526 },
    { score: 655, rank: 38755, percentile: 0.7782 },
    { score: 650, rank: 40030, percentile: 0.8038 },
    { score: 645, rank: 41305, percentile: 0.8294 },
    { score: 640, rank: 42580, percentile: 0.855 },
    { score: 635, rank: 43855, percentile: 0.8806 },
    { score: 630, rank: 45120, percentile: 0.906 },
    { score: 625, rank: 46370, percentile: 0.9311 },
    { score: 620, rank: 47620, percentile: 0.9562 },
    { score: 615, rank: 48870, percentile: 0.9813 },
    { score: 611, rank: 49900, percentile: 1 },
    { score: 607, rank: 50440, percentile: 1.0129 }
  ]
};

const TARGET_QUOTA_DATA = {
  sourceSchool: "西安市高新一中初级中学",
  year: 2025,
  totalQuota: 349,
  sourceFile: "高新一中定向招生名额整理表.xlsx",
  quotas: [
    { code: "010430", schoolName: "西安高新第一中学", quota: 50, districtPlan: 173, share: 0.289, rank: 1 },
    { code: "010425", schoolName: "西安博迪学校", quota: 30, districtPlan: 485, share: 0.0619, rank: 2 },
    { code: "010448", schoolName: "西安市高新第二高级中学", quota: 23, districtPlan: 225, share: 0.1022, rank: 3 },
    { code: "010443", schoolName: "西安交通大学附属中学航天高级中学", quota: 22, districtPlan: 323, share: 0.0681, rank: 4 },
    { code: "010444", schoolName: "西安市曲江第二中学", quota: 15, districtPlan: 224, share: 0.067, rank: 5 },
    { code: "010413", schoolName: "西安电子科技中学", quota: 13, districtPlan: 198, share: 0.0657, rank: 6 },
    { code: "010434", schoolName: "西安高新唐南中学", quota: 12, districtPlan: 192, share: 0.0625, rank: 7 },
    { code: "010437", schoolName: "西安雁南中学", quota: 12, districtPlan: 193, share: 0.0622, rank: 8 },
    { code: "010403", schoolName: "西安市第五十三中学", quota: 11, districtPlan: 160, share: 0.0688, rank: 9 },
    { code: "010402", schoolName: "西安市第四十六中学", quota: 10, districtPlan: 151, share: 0.0662, rank: 10 },
    { code: "010409", schoolName: "西安东仪中学", quota: 10, districtPlan: 150, share: 0.0667, rank: 11 },
    { code: "010527", schoolName: "陕西省西安中学", quota: 10, districtPlan: 154, share: 0.0649, rank: 12 },
    { code: "010401", schoolName: "西安市第四十五中学", quota: 9, districtPlan: 145, share: 0.0621, rank: 13 },
    { code: "010427", schoolName: "西安太白学校", quota: 9, districtPlan: 140, share: 0.0643, rank: 14 },
    { code: "010452", schoolName: "西安市阳光中学", quota: 9, districtPlan: 130, share: 0.0692, rank: 15 },
    { code: "010436", schoolName: "西安崇是中学", quota: 7, districtPlan: 110, share: 0.0636, rank: 16 },
    { code: "010205", schoolName: "西安市第八十九中学", quota: 5, districtPlan: 67, share: 0.0746, rank: 17 },
    { code: "010215", schoolName: "西安市西光中学", quota: 5, districtPlan: 61, share: 0.082, rank: 18 },
    { code: "010312", schoolName: "西安市远东第一中学", quota: 5, districtPlan: 55, share: 0.0909, rank: 19 },
    { code: "010313", schoolName: "西安市庆安高级中学", quota: 5, districtPlan: 63, share: 0.0794, rank: 20 },
    { code: "010320", schoolName: "西安市第七十中学", quota: 5, districtPlan: 63, share: 0.0794, rank: 21 },
    { code: "010104", schoolName: "西安市第三中学", quota: 4, districtPlan: 56, share: 0.0714, rank: 22 },
    { code: "010301", schoolName: "西安市第一中学", quota: 4, districtPlan: 58, share: 0.069, rank: 23 },
    { code: "010441", schoolName: "西安市曲江第一中学", quota: 4, districtPlan: 65, share: 0.0615, rank: 24 },
    { code: "010449", schoolName: "西安市航天城第一中学", quota: 4, districtPlan: 53, share: 0.0755, rank: 25 },
    { code: "010505", schoolName: "西安市第六十六中学", quota: 4, districtPlan: 56, share: 0.0714, rank: 26 },
    { code: "010506", schoolName: "西安市第七十五中学", quota: 4, districtPlan: 64, share: 0.0625, rank: 27 },
    { code: "010510", schoolName: "西安市西航一中", quota: 4, districtPlan: 56, share: 0.0714, rank: 28 },
    { code: "010530", schoolName: "西安高级中学", quota: 4, districtPlan: 60, share: 0.0667, rank: 29 },
    { code: "010105", schoolName: "西安市第六中学", quota: 3, districtPlan: 42, share: 0.0714, rank: 30 },
    { code: "010112", schoolName: "西安市第二十六中学", quota: 3, districtPlan: 44, share: 0.0682, rank: 31 },
    { code: "010118", schoolName: "西安市铁一中学", quota: 3, districtPlan: 57, share: 0.0526, rank: 32 },
    { code: "010202", schoolName: "西安市第八十三中学", quota: 3, districtPlan: 58, share: 0.0517, rank: 33 },
    { code: "010316", schoolName: "西安市远东第二中学", quota: 3, districtPlan: 57, share: 0.0526, rank: 34 },
    { code: "010406", schoolName: "西安市第八十五中学", quota: 3, districtPlan: 48, share: 0.0625, rank: 35 },
    { code: "010609", schoolName: "西安市东城第一中学", quota: 3, districtPlan: 53, share: 0.0566, rank: 36 },
    { code: "010618", schoolName: "西安铁一中滨河高级中学", quota: 3, districtPlan: 57, share: 0.0526, rank: 37 },
    { code: "010102", schoolName: "西北工业大学附属中学", quota: 2, districtPlan: 65, share: 0.0308, rank: 38 },
    { code: "010408", schoolName: "西安电子科技大学附属中学", quota: 2, districtPlan: 28, share: 0.0714, rank: 39 },
    { code: "010531", schoolName: "西安市经开第一中学", quota: 2, districtPlan: 48, share: 0.0417, rank: 40 },
    { code: "011405", schoolName: "陕西省西咸新区秦汉中学", quota: 2, districtPlan: 33, share: 0.0606, rank: 41 },
    { code: "010119", schoolName: "西北大学附属中学", quota: 1, districtPlan: 13, share: 0.0769, rank: 42 },
    { code: "010122", schoolName: "西安建筑科技大学附属中学", quota: 1, districtPlan: 18, share: 0.0556, rank: 43 },
    { code: "010208", schoolName: "西安市第三十中学", quota: 1, districtPlan: 16, share: 0.0625, rank: 44 },
    { code: "010405", schoolName: "西安市育才中学", quota: 1, districtPlan: 35, share: 0.0286, rank: 45 },
    { code: "010415", schoolName: "西安市航天中学", quota: 1, districtPlan: 43, share: 0.0233, rank: 46 },
    { code: "010440", schoolName: "西安高新第三中学", quota: 1, districtPlan: 56, share: 0.0179, rank: 47 },
    { code: "011401", schoolName: "西安市车辆中学", quota: 1, districtPlan: 18, share: 0.0556, rank: 48 },
    { code: "011402", schoolName: "西安高新一中沣东中学", quota: 1, districtPlan: 23, share: 0.0435, rank: 49 },
    { code: "010103", schoolName: "西安交通大学附属中学", quota: 0, districtPlan: 27, share: 0, rank: 50 },
    { code: "010407", schoolName: "陕西师范大学附属中学", quota: 0, districtPlan: 33, share: 0, rank: 51 }
  ]
};

const SCHOOL_OUTCOME_DATA = {
  minYear: 2021,
  xgdfz: {
    year: 2024,
    firstTierRate: null,
    sixHundredRate: 0.766,
    highScoreCount: 927,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安知名高中600分以上占比",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341746.html",
    note: "600分占比为第三方按高考喜报与三年前录取人数估算，非学校官方完整升学率。"
  },
  tieyi: {
    year: 2024,
    firstTierRate: null,
    sixHundredRate: 0.8,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安知名高中600分以上占比",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341746.html",
    note: "600分占比为第三方按高考喜报与三年前录取人数估算，非学校官方完整升学率。"
  },
  jiaodafz: {
    year: 2024,
    firstTierRate: null,
    sixHundredRate: 0.723,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安知名高中600分以上占比",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341746.html",
    note: "600分占比为第三方按高考喜报与三年前录取人数估算，非学校官方完整升学率。"
  },
  gaoxin1: {
    year: 2024,
    firstTierRate: null,
    sixHundredRate: 0.925,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安知名高中600分以上占比",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341746.html",
    note: "另有秦学教育整理称2023年高新一中文科600分以上占比89.7%、理科95.3%；此处采用中招网总占比口径。"
  },
  sdfz: {
    year: 2024,
    firstTierRate: null,
    sixHundredRate: 0.58,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安知名高中600分以上占比",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341746.html",
    note: "600分占比为第三方按高考喜报与三年前录取人数估算，非学校官方完整升学率。"
  },
  "tieyi-binhe": {
    year: 2024,
    firstTierRate: 0.99,
    sixHundredRate: 0.7,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安十大高中盘点",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341867.html",
    note: "2024年第三方整理称一本上线率99%、600分以上占比约70%；另有2023年口径为600分以上64.5%。"
  },
  xasan: {
    year: 2023,
    firstTierRate: 0.988,
    sixHundredRate: 0.289,
    highScoreCount: 143,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安十大高中盘点",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341867.html",
    note: "2023年489人参加高考，600分以上143人；另有第三方整理给出600分占比28.9%。"
  },
  changan1: {
    year: 2024,
    firstTierRate: 0.975,
    sixHundredRate: null,
    highScoreCount: 228,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安十大高中盘点",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341867.html",
    note: "2024年参考791人，一本上线771人，600分以上228人；同站另文提到600分占比22.9%，口径存在差异，此处优先展示人数。"
  },
  "83": {
    year: 2024,
    firstTierRate: 0.97,
    sixHundredRate: 0.195,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安十大高中盘点",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341867.html",
    note: "2024年第三方整理称一本上线率97%、600分以上占比19.5%；仅展示近5年数据。"
  },
  "gx-fengdong": {
    year: 2023,
    firstTierRate: null,
    sixHundredRate: null,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "秦学教育：西安高新系高中介绍",
    sourceUrl: "https://js.qinxue100.com/jiangsu-news-gz/details_335262.html",
    note: "公开整理为文理分列：2023年高新沣东一本率理科95.15%、文科85.71%；暂无总口径，未折算。"
  },
  qujiang1: {
    year: 2024,
    firstTierRate: 0.972,
    sixHundredRate: 0.209,
    highScoreCount: 60,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安十大高中盘点",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341867.html",
    note: "2024年高考人数287人，一本上线率97.2%，600分以上60人，占比约20.9%。"
  },
  "26": {
    year: 2023,
    firstTierRate: 0.967,
    sixHundredRate: 0.196,
    highScoreCount: 52,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "西安中考网：西安市第二十六中学2023高考成绩",
    sourceUrl: "https://www.hytale-nav.com/xydt/3636.html",
    note: "2023年高三265人，一本上线257人，600分以上52人。"
  },
  gx2: {
    year: 2023,
    firstTierRate: null,
    sixHundredRate: 0.1,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "中招网：西安知名高中600分以上占比",
    sourceUrl: "https://www.zhongzhao.org.cn/news/show-341746.html",
    note: "中招网整理称高新二中600分以上占比10%；秦学教育另称2023年一本率理科93.4%、文科90%，暂无总口径。"
  },
  tangnan: {
    year: 2023,
    firstTierRate: 0.94,
    sixHundredRate: null,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: "搜狐转载：西安高新唐南中学2024年新高一招生公告",
    sourceUrl: "https://www.sohu.com/a/790812555_121124028",
    note: "文章内容来源标注为“西安高新唐南中学”公众号；披露2023年高考一本上线率94%，985高校录取60余人。"
  },
  default: {
    year: null,
    firstTierRate: null,
    sixHundredRate: null,
    highScoreCount: null,
    doubleFirstClassRate: null,
    undergraduateRate: null,
    sourceTitle: null,
    sourceUrl: null,
    note: "近5年出口数据待补：暂未查到2021-2025届稳定公开资料，请以学校官方公众号、招生简章或家长会材料为准。"
  }
};

const SCHOOL_CLASS_TYPE_DATA = {
  xgdfz: {
    sourceTitle: "西工大附中班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开升学资料整理，具体班数以当年招生简章和入学分班为准。",
    classes: [
      { name: "钱学森班", count: null },
      { name: "创新班", count: null },
      { name: "实验班", count: null }
    ]
  },
  tieyi: {
    sourceTitle: "铁一中班型公开资料整理",
    sourceUrl: "",
    note: "不同校区和年份班型名称会调整，具体以当年招生说明为准。",
    classes: [
      { name: "钱学森班", count: null },
      { name: "创新班", count: null },
      { name: "重点班", count: null }
    ]
  },
  jiaodafz: {
    sourceTitle: "交大附中班型公开资料整理",
    sourceUrl: "",
    note: "公开资料多为班型名称，班数缺少稳定公开口径。",
    classes: [
      { name: "少年班", count: null },
      { name: "创新实验班", count: null },
      { name: "重点班", count: null }
    ]
  },
  gaoxin1: {
    sourceTitle: "高新一中班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开升学资料整理，具体班数以当年高一分班为准。",
    classes: [
      { name: "创新班", count: null },
      { name: "重点班", count: null },
      { name: "实验班", count: null }
    ]
  },
  sdfz: {
    sourceTitle: "师大附中班型公开资料整理",
    sourceUrl: "",
    note: "班型名称会随年份调整，班数未见统一公开口径。",
    classes: [
      { name: "创新实验班", count: null },
      { name: "重点班", count: null },
      { name: "平行班", count: null }
    ]
  },
  "tieyi-binhe": {
    sourceTitle: "铁一滨河班型公开资料整理",
    sourceUrl: "",
    note: "集团校班型名称与本部相近，具体班数以当年学校安排为准。",
    classes: [
      { name: "钱学森班", count: null },
      { name: "创新班", count: null },
      { name: "重点班", count: null }
    ]
  },
  xazx: {
    sourceTitle: "西安中学班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开招生与升学资料整理。",
    classes: [
      { name: "创新实验班", count: null },
      { name: "重点班", count: null },
      { name: "平行班", count: null }
    ]
  },
  xasan: {
    sourceTitle: "西安市第三中学班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，班数暂未查到稳定公开口径。",
    classes: [
      { name: "春笋班", count: null },
      { name: "重点班", count: null },
      { name: "实验班", count: null }
    ]
  },
  xayi: {
    sourceTitle: "西安市第一中学班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，具体以学校当年安排为准。",
    classes: [
      { name: "宏志班", count: null },
      { name: "重点班", count: null },
      { name: "平行班", count: null }
    ]
  },
  changan1: {
    sourceTitle: "长安一中班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，班数暂未查到稳定公开口径。",
    classes: [
      { name: "重点班", count: null },
      { name: "实验班", count: null },
      { name: "平行班", count: null }
    ]
  },
  "83": {
    sourceTitle: "西安市第八十三中学班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，具体班数以学校当年安排为准。",
    classes: [
      { name: "春笋班", count: null },
      { name: "创新班", count: null },
      { name: "重点班", count: null }
    ]
  },
  qujiang1: {
    sourceTitle: "曲江一中班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，班数暂未查到稳定公开口径。",
    classes: [
      { name: "创新实验班", count: null },
      { name: "重点班", count: null },
      { name: "平行班", count: null }
    ]
  },
  "26": {
    sourceTitle: "西安市第二十六中学班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，具体以学校当年安排为准。",
    classes: [
      { name: "重点班", count: null },
      { name: "实验班", count: null },
      { name: "平行班", count: null }
    ]
  },
  "89": {
    sourceTitle: "西安市第八十九中学班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，具体以学校当年安排为准。",
    classes: [
      { name: "创新实验班", count: null },
      { name: "重点班", count: null },
      { name: "平行班", count: null }
    ]
  },
  jingkai1: {
    sourceTitle: "经开一中班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，班数暂未查到稳定公开口径。",
    classes: [
      { name: "创新班", count: null },
      { name: "重点班", count: null },
      { name: "平行班", count: null }
    ]
  },
  "tieyi-guoji": {
    sourceTitle: "铁一中国际合作学校班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，具体班数以学校当年安排为准。",
    classes: [
      { name: "国际课程班", count: null },
      { name: "重点班", count: null }
    ]
  },
  "jiaoda-hangtian": {
    sourceTitle: "交大航天班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，具体班数以学校当年安排为准。",
    classes: [
      { name: "创新实验班", count: null },
      { name: "重点班", count: null },
      { name: "平行班", count: null }
    ]
  },
  gx2: {
    sourceTitle: "高新二高班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，班数暂未查到稳定公开口径。",
    classes: [
      { name: "创新班", count: null },
      { name: "重点班", count: null },
      { name: "平行班", count: null }
    ]
  },
  tangnan: {
    sourceTitle: "高新唐南中学班型公开资料整理",
    sourceUrl: "",
    note: "班型名称来自公开资料，具体班数以学校当年安排为准。",
    classes: [
      { name: "重点班", count: null },
      { name: "实验班", count: null },
      { name: "平行班", count: null }
    ]
  },
  default: {
    sourceTitle: null,
    sourceUrl: null,
    note: "班型待补：暂未查到稳定公开资料，建议以学校当年招生简章、家长会或高一分班通知为准。",
    classes: []
  }
};

const SCHOOL_DATA = [
  {
    id: "xgdfz",
    name: "西北工业大学附属中学",
    shortName: "西工大附中",
    code: "010102",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["五大名校", "强竞赛", "高热度"],
    targeted: true,
    lines: { 2025: 785.7, 2024: 664, 2023: 672 }
  },
  {
    id: "tieyi",
    name: "西安市铁一中学",
    shortName: "铁一中",
    code: "010118",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["五大名校", "强理科", "高热度"],
    targeted: true,
    lines: { 2025: 782.5, 2024: 666, 2023: 671 }
  },
  {
    id: "jiaodafz",
    name: "西安交通大学附属中学",
    shortName: "交大附中",
    code: "010103",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["五大名校", "综合强校"],
    targeted: true,
    lines: { 2025: 780.8, 2024: 662.5, 2023: 667 }
  },
  {
    id: "gaoxin1",
    name: "西安高新第一中学",
    shortName: "高新一中",
    code: "010430",
    batch: "第一批次",
    level: "省示范",
    ownership: "民办",
    district: "高新区",
    campus: "本部",
    tags: ["五大名校", "民办强校"],
    targeted: true,
    lines: { 2025: 779.8, 2024: 655.9, 2023: 671 }
  },
  {
    id: "sdfz",
    name: "陕西师范大学附属中学",
    shortName: "师大附中",
    code: "010407",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "雁塔区",
    campus: "本部",
    tags: ["五大名校", "均衡"],
    targeted: true,
    lines: { 2025: 776, 2024: 657.3, 2023: 664 }
  },
  {
    id: "tieyi-binhe",
    name: "西安铁一中滨河高级中学",
    shortName: "铁一滨河",
    code: "010618",
    batch: "第一批次",
    level: "省示范",
    ownership: "民办",
    district: "浐灞国际港",
    campus: "滨河",
    tags: ["集团校", "民办"],
    targeted: true,
    lines: { 2025: 775, 2024: 657.5, 2023: 663 }
  },
  {
    id: "xazx",
    name: "陕西省西安中学",
    shortName: "西安中学",
    code: "010527",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "经开区",
    campus: "本部",
    tags: ["省属", "公办"],
    targeted: true,
    lines: { 2025: 766.3, 2024: 648.9, 2023: 657 }
  },
  {
    id: "xasan",
    name: "西安市第三中学",
    shortName: "市三中",
    code: "010104",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["老牌强校", "公办"],
    targeted: true,
    lines: { 2025: 766, 2024: 647.7, 2023: 655 }
  },
  {
    id: "xayi",
    name: "西安市第一中学",
    shortName: "市一中",
    code: "010301",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["老牌强校", "宏志班"],
    targeted: true,
    lines: { 2025: 759.8, 2024: 641.5, 2023: 653 }
  },
  {
    id: "changan1",
    name: "西安市长安区第一中学",
    shortName: "长安一中",
    code: "010901",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "长安区",
    campus: "本部",
    tags: ["区域强校"],
    targeted: true,
    lines: { 2025: 758.3, 2024: 630, 2023: 639 }
  },
  {
    id: "83",
    name: "西安市第八十三中学",
    shortName: "83中",
    code: "010202",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["宏志班", "公办"],
    targeted: true,
    lines: { 2025: 756.4, 2024: 638.5, 2023: 650 }
  },
  {
    id: "85",
    name: "西安市第八十五中学",
    shortName: "85中",
    code: "010406",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "雁塔区",
    campus: "本部",
    tags: ["公办", "南郊"],
    targeted: true,
    lines: { 2025: 755.8, 2024: 638.4, 2023: 650 }
  },
  {
    id: "gx-fengdong",
    name: "西安高新一中沣东中学",
    shortName: "高新沣东",
    code: "010533",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "西咸新区",
    campus: "沣东",
    tags: ["集团校", "新区"],
    targeted: true,
    lines: { 2025: 753, 2023: 642 }
  },
  {
    id: "qujiang1",
    name: "西安市曲江第一中学",
    shortName: "曲江一中",
    code: "010441",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "曲江新区",
    campus: "本部",
    tags: ["热门公办", "南郊"],
    targeted: true,
    lines: { 2025: 750.5, 2024: 638.4, 2023: 649 }
  },
  {
    id: "26",
    name: "西安市第二十六中学",
    shortName: "26中",
    code: "010112",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办", "城南"],
    targeted: true,
    lines: { 2025: 748.8, 2024: 635.3, 2023: 646 }
  },
  {
    id: "89",
    name: "西安市第八十九中学",
    shortName: "89中",
    code: "010205",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["公办", "城东"],
    targeted: true,
    lines: { 2025: 748.6, 2024: 634.9, 2023: 649 }
  },
  {
    id: "jingkai1",
    name: "西安市经开第一中学",
    shortName: "经开一中",
    code: "010531",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "经开区",
    campus: "本部",
    tags: ["开发区", "公办"],
    targeted: true,
    lines: { 2025: 746.8, 2024: 629, 2023: 641 }
  },
  {
    id: "xdfz",
    name: "西北大学附属中学",
    shortName: "西大附中",
    code: "010119",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["大学附中", "公办"],
    targeted: true,
    lines: { 2025: 739.8, 2024: 624.6, 2023: 645 }
  },
  {
    id: "qinhan",
    name: "西咸新区秦汉中学",
    shortName: "秦汉中学",
    code: "010548",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "西咸新区",
    campus: "秦汉",
    tags: ["新区", "公办"],
    targeted: true,
    lines: { 2025: 735.8, 2024: 621.1, 2023: 630 }
  },
  {
    id: "xagj",
    name: "西安高级中学",
    shortName: "西安高级",
    code: "010530",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["老牌公办"],
    targeted: true,
    lines: { 2025: 734.4, 2024: 623.8, 2023: 646 }
  },
  {
    id: "6",
    name: "西安市第六中学",
    shortName: "6中",
    code: "010105",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 728.4, 2024: 618.3, 2023: 635 }
  },
  {
    id: "xiguang",
    name: "西安市西光中学",
    shortName: "西光中学",
    code: "010215",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 728.3, 2024: 621.5, 2023: 630 }
  },
  {
    id: "gx3",
    name: "西安高新第三中学",
    shortName: "高新三中",
    code: "010440",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "高新区",
    campus: "本部",
    tags: ["高新系", "公办"],
    targeted: true,
    lines: { 2025: 728, 2024: 617.8, 2023: 635 }
  },
  {
    id: "75",
    name: "西安市第七十五中学",
    shortName: "75中",
    code: "010506",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: true,
    lines: { 2025: 727, 2024: 617.6, 2023: 632 }
  },
  {
    id: "xd-fz",
    name: "西安电子科技大学附属中学",
    shortName: "西电附中",
    code: "010408",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "雁塔区",
    campus: "本部",
    tags: ["大学附中", "公办"],
    targeted: true,
    lines: { 2025: 724, 2024: 611, 2023: 640 }
  },
  {
    id: "dongcheng1",
    name: "西安市东城第一中学",
    shortName: "东城一中",
    code: "010609",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "灞桥区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 722.4, 2024: 608.4, 2023: 629 }
  },
  {
    id: "jdfz",
    name: "西安建筑科技大学附属中学",
    shortName: "建大附中",
    code: "010122",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["大学附中"],
    targeted: true,
    lines: { 2025: 720.5, 2024: 608, 2023: 630 }
  },
  {
    id: "xihang1",
    name: "西安市西航一中",
    shortName: "西航一中",
    code: "010510",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: true,
    lines: { 2025: 719, 2024: 609.3, 2023: 623 }
  },
  {
    id: "yuandong1",
    name: "西安市远东第一中学",
    shortName: "远东一中",
    code: "010312",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["城西", "公办"],
    targeted: true,
    lines: { 2025: 712.2, 2024: 597.9, 2023: 621 }
  },
  {
    id: "qingan",
    name: "西安市庆安高级中学",
    shortName: "庆安高级",
    code: "010313",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["城西", "公办"],
    targeted: true,
    lines: { 2025: 711.4, 2024: 597.9, 2023: 627 }
  },
  {
    id: "yuandong2",
    name: "西安市远东第二中学",
    shortName: "远东二中",
    code: "010316",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["城西", "公办"],
    targeted: true,
    lines: { 2025: 710.6, 2024: 595.5, 2023: 616 }
  },
  {
    id: "hangtian",
    name: "西安市航天中学",
    shortName: "航天中学",
    code: "010415",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "航天基地",
    campus: "本部",
    tags: ["航天", "公办"],
    targeted: true,
    lines: { 2025: 706.5, 2024: 594.3, 2023: 621 }
  },
  {
    id: "66",
    name: "西安市第六十六中学",
    shortName: "66中",
    code: "010505",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: true,
    lines: { 2025: 700.3, 2024: 592, 2023: 616 }
  },
  {
    id: "70",
    name: "西安市第七十中学",
    shortName: "70中",
    code: "010320",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["城西", "公办"],
    targeted: true,
    lines: { 2025: 696.6, 2024: 589.9, 2023: 614 }
  },
  {
    id: "yucai",
    name: "西安市育才中学",
    shortName: "育才中学",
    code: "010405",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 694.9, 2024: 586, 2023: 614 }
  },
  {
    id: "cheliang",
    name: "西安市车辆中学",
    shortName: "车辆中学",
    code: "010513",
    batch: "第一批次",
    level: "省示范",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北"],
    targeted: true,
    lines: { 2025: 687.9, 2024: 575.5, 2023: 598 }
  },
  {
    id: "tieyi-guoji",
    name: "西安铁一中国际合作学校",
    shortName: "铁一国际",
    code: "010128",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "碑林区",
    campus: "国际合作",
    tags: ["集团校", "民办"],
    targeted: true,
    lines: { 2025: 774.4, 2023: 663 }
  },
  {
    id: "tieyi-lugang",
    name: "铁一中陆港高级中学",
    shortName: "铁一陆港",
    code: "010617",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "浐灞国际港",
    campus: "陆港",
    tags: ["集团校", "新校"],
    targeted: false,
    lines: { 2025: 764.9, 2023: 655 }
  },
  {
    id: "chongshi",
    name: "西安崇是中学",
    shortName: "崇是中学",
    code: "010436",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "雁塔区",
    campus: "本部",
    tags: ["师大系", "民办"],
    targeted: true,
    lines: { 2025: 764.5, 2023: 650 }
  },
  {
    id: "tieyi-jinwan",
    name: "西咸新区铁一中金湾中学",
    shortName: "铁一金湾",
    code: "010617",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "西咸新区",
    campus: "金湾",
    tags: ["集团校", "新区"],
    targeted: false,
    lines: { 2025: 761.5, 2023: 648 }
  },
  {
    id: "chuangxingang",
    name: "西安市创新港中学",
    shortName: "创新港中学",
    code: "010545",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "西咸新区",
    campus: "创新港",
    tags: ["新区", "公办"],
    targeted: false,
    lines: { 2025: 761.3, 2023: 648 }
  },
  {
    id: "gx-lugang",
    name: "高新一中陆港中学",
    shortName: "高新陆港",
    code: "010623",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "浐灞国际港",
    campus: "陆港",
    tags: ["高新系", "新校"],
    targeted: false,
    lines: { 2025: 752.3 }
  },
  {
    id: "jiaoda-hangtian",
    name: "西安交通大学附属中学航天高级中学",
    shortName: "交大航天",
    code: "010443",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "航天基地",
    campus: "航天",
    tags: ["交大系", "民办"],
    targeted: true,
    lines: { 2025: 748.5, 2023: 652 }
  },
  {
    id: "konggang",
    name: "西咸新区空港实验高级中学",
    shortName: "空港实验",
    code: "010547",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "西咸新区",
    campus: "空港",
    tags: ["新区", "公办"],
    targeted: false,
    lines: { 2025: 747.4 }
  },
  {
    id: "gx2",
    name: "西安市高新第二高级中学",
    shortName: "高新二高",
    code: "010448",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "高新区",
    campus: "本部",
    tags: ["高新系", "公办"],
    targeted: true,
    lines: { 2025: 745.5, 2023: 630 }
  },
  {
    id: "taiyilu",
    name: "西安市太乙路中学",
    shortName: "太乙路中学",
    code: "010121",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 745.3 }
  },
  {
    id: "gx-shiyan",
    name: "西安高新一中实验中学",
    shortName: "高新实验",
    code: "010453",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "高新区",
    campus: "实验",
    tags: ["高新系", "公办"],
    targeted: false,
    lines: { 2025: 742.7 }
  },
  {
    id: "89-fen",
    name: "西安市第八十九中学分校",
    shortName: "89中分校",
    code: "010219",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "新城区",
    campus: "分校",
    tags: ["公办"],
    targeted: false,
    lines: { 2025: 741.3 }
  },
  {
    id: "8",
    name: "西安市第八中学",
    shortName: "8中",
    code: "010131",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 741.2, 2023: 634 }
  },
  {
    id: "htc1",
    name: "西安市航天城第一中学",
    shortName: "航天城一中",
    code: "010449",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "航天基地",
    campus: "本部",
    tags: ["航天", "公办"],
    targeted: true,
    lines: { 2025: 739.8, 2023: 635 }
  },
  {
    id: "htc2",
    name: "西安市航天城第二中学",
    shortName: "航天城二中",
    code: "010923",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "航天基地",
    campus: "本部",
    tags: ["航天", "公办"],
    targeted: false,
    lines: { 2025: 739.5, 2023: 632 }
  },
  {
    id: "sdfz-lugang",
    name: "陕西师范大学陆港高级中学",
    shortName: "师大陆港",
    code: "010624",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "浐灞国际港",
    campus: "陆港",
    tags: ["师大系", "新校"],
    targeted: false,
    lines: { 2025: 734 }
  },
  {
    id: "guojigang",
    name: "西安国际港务区实验中学",
    shortName: "国际港实验",
    code: "010625",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "浐灞国际港",
    campus: "本部",
    tags: ["开发区", "公办"],
    targeted: false,
    lines: { 2025: 730 }
  },
  {
    id: "tangnan",
    name: "西安高新唐南中学",
    shortName: "高新唐南",
    code: "010434",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "高新区",
    campus: "本部",
    location: { lat: 34.226692, lng: 108.906833 },
    tags: ["高新系", "民办"],
    targeted: true,
    lines: { 2025: 729.8 }
  },
  {
    id: "6-fen",
    name: "西安市第六中学分校",
    shortName: "6中分校",
    code: "010145",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "分校",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 729.5, 2023: 627 }
  },
  {
    id: "qujiang2",
    name: "西安市曲江第二中学",
    shortName: "曲江二中",
    code: "010444",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "曲江新区",
    campus: "本部",
    tags: ["曲江", "公办"],
    targeted: true,
    lines: { 2025: 729 }
  },
  {
    id: "55",
    name: "西安市第五十五中学",
    shortName: "55中",
    code: "010603",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "灞桥区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 724.8, 2023: 632 }
  },
  {
    id: "yanta2",
    name: "西安市雁塔区第二中学",
    shortName: "雁塔二中",
    code: "010451",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "雁塔区",
    campus: "本部",
    location: { lat: 34.193386, lng: 108.919683 },
    tags: ["雁塔", "公办"],
    targeted: false,
    lines: { 2025: 720, 2023: 618 }
  },
  {
    id: "2",
    name: "西安市第二中学",
    shortName: "2中",
    code: "010108",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 719, 2023: 608 }
  },
  {
    id: "hanguang",
    name: "西安市含光中学",
    shortName: "含光中学",
    code: "010106",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 718.5 }
  },
  {
    id: "72",
    name: "西安市第七十二中学",
    shortName: "72中",
    code: "010209",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["西光分校", "公办"],
    targeted: true,
    lines: { 2025: 718.4 }
  },
  {
    id: "82",
    name: "西安市第八十二中学",
    shortName: "82中",
    code: "010114",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 716.8, 2023: 619 }
  },
  {
    id: "xd-chanba",
    name: "西安市西大附中浐灞中学",
    shortName: "西大浐灞",
    code: "010532",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "浐灞国际港",
    campus: "浐灞",
    tags: ["西大系", "公办"],
    targeted: true,
    lines: { 2025: 716, 2023: 619 }
  },
  {
    id: "gx4",
    name: "高新区第四完全中学",
    shortName: "高新四完中",
    code: "011004",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "高新区",
    campus: "本部",
    location: { lat: 34.22515, lng: 108.89019 },
    tags: ["高新", "公办"],
    targeted: false,
    lines: { 2025: 716 }
  },
  {
    id: "yangguang",
    name: "西安市阳光中学",
    shortName: "阳光中学",
    code: "010452",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "雁塔区",
    campus: "本部",
    tags: ["民办"],
    targeted: true,
    lines: { 2025: 711, 2023: 605 }
  },
  {
    id: "jingkai3",
    name: "西安市经开第三中学",
    shortName: "经开三中",
    code: "010535",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "经开区",
    campus: "本部",
    tags: ["经开", "公办"],
    targeted: true,
    lines: { 2025: 710.1, 2023: 615 }
  },
  {
    id: "wuhuan",
    name: "西安市五环中学",
    shortName: "五环中学",
    code: "010610",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "灞桥区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 708, 2023: 615 }
  },
  {
    id: "huanghe",
    name: "西安市黄河中学",
    shortName: "黄河中学",
    code: "010214",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 703.2, 2023: 612 }
  },
  {
    id: "48",
    name: "西安市第四十八中学",
    shortName: "48中",
    code: "010503",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: true,
    lines: { 2025: 701, 2023: 592 }
  },
  {
    id: "zhongtie",
    name: "西安市中铁中学",
    shortName: "中铁中学",
    code: "010107",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 697, 2023: 602 }
  },
  {
    id: "yannan",
    name: "西安雁南中学",
    shortName: "雁南中学",
    code: "010437",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "雁塔区",
    campus: "本部",
    tags: ["民办", "南郊"],
    targeted: true,
    lines: { 2025: 696.1, 2023: 597 }
  },
  {
    id: "chanba2",
    name: "西安市浐灞第二中学",
    shortName: "浐灞二中",
    code: "010550",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "浐灞国际港",
    campus: "本部",
    tags: ["浐灞", "公办"],
    targeted: false,
    lines: { 2025: 696, 2023: 596 }
  },
  {
    id: "jinghe1",
    name: "西咸新区泾河新城第一中学",
    shortName: "泾河一中",
    code: "010546",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "西咸新区",
    campus: "泾河",
    tags: ["新区", "公办"],
    targeted: false,
    lines: { 2025: 690.3, 2023: 596 }
  },
  {
    id: "86",
    name: "西安市第八十六中学",
    shortName: "86中",
    code: "010115",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 688, 2023: 605 }
  },
  {
    id: "lianhu1",
    name: "西安市莲湖第一中学",
    shortName: "莲湖一中",
    code: "010321",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["城西", "公办"],
    targeted: false,
    lines: { 2025: 687 }
  },
  {
    id: "xidian",
    name: "西安市西电中学",
    shortName: "西电中学",
    code: "010310",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 685.1 }
  },
  {
    id: "huashan",
    name: "西安市华山中学",
    shortName: "华山中学",
    code: "010216",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 684, 2023: 595 }
  },
  {
    id: "qinghua",
    name: "西安市庆华中学",
    shortName: "庆华中学",
    code: "010615",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "灞桥区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 683.6, 2023: 597 }
  },
  {
    id: "71",
    name: "西安市第七十一中学",
    shortName: "71中",
    code: "010113",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 683.5, 2023: 590 }
  },
  {
    id: "11",
    name: "西安市第十一中学",
    shortName: "11中",
    code: "010501",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: true,
    lines: { 2025: 680.7, 2023: 605 }
  },
  {
    id: "dongyi",
    name: "西安东仪中学",
    shortName: "东仪中学",
    code: "010409",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "雁塔区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 679.9 }
  },
  {
    id: "34",
    name: "西安市第三十四中学",
    shortName: "34中",
    code: "010602",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "灞桥区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 676.8 }
  },
  {
    id: "xagdfz",
    name: "西安工业大学附中",
    shortName: "西工院附中",
    code: "010120",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "碑林区",
    campus: "本部",
    tags: ["大学附中"],
    targeted: true,
    lines: { 2025: 676.5, 2023: 585 }
  },
  {
    id: "taibai",
    name: "西安太白学校",
    shortName: "太白学校",
    code: "010427",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "雁塔区",
    campus: "本部",
    tags: ["民办"],
    targeted: true,
    lines: { 2025: 676.3 }
  },
  {
    id: "30",
    name: "西安市第三十中学",
    shortName: "30中",
    code: "010208",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["公办"],
    targeted: true,
    lines: { 2025: 675.4, 2023: 590 }
  },
  {
    id: "jinyuan",
    name: "西安锦园中学",
    shortName: "锦园中学",
    code: "010526",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "未央区",
    campus: "本部",
    tags: ["民办"],
    targeted: true,
    lines: { 2025: 671, 2023: 580 }
  },
  {
    id: "tengxin",
    name: "西安藤信高级中学",
    shortName: "藤信高中",
    code: "010424",
    batch: "第二批次",
    level: "普通",
    ownership: "民办",
    district: "雁塔区",
    campus: "本部",
    tags: ["民办"],
    targeted: false,
    lines: { 2025: 670 }
  },
  {
    id: "58",
    name: "西安市第五十八中学",
    shortName: "58中",
    code: "010512",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: false,
    lines: { 2025: 667.3, 2023: 565 }
  },
  {
    id: "45",
    name: "西安市第四十五中学",
    shortName: "45中",
    code: "010401",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "雁塔区",
    campus: "本部",
    tags: ["南郊", "公办"],
    targeted: true,
    lines: { 2025: 667 }
  },
  {
    id: "daminggong",
    name: "西安市大明宫中学",
    shortName: "大明宫中学",
    code: "010210",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: true,
    lines: { 2025: 666.8, 2023: 565 }
  },
  {
    id: "kunlun",
    name: "西安市昆仑中学",
    shortName: "昆仑中学",
    code: "010217",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 664.6, 2023: 595 }
  },
  {
    id: "44",
    name: "西安市第四十四中学",
    shortName: "44中",
    code: "010306",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["城西", "公办"],
    targeted: true,
    lines: { 2025: 662 }
  },
  {
    id: "handu",
    name: "西安市汉都新苑中学",
    shortName: "汉都新苑",
    code: "010511",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: false,
    lines: { 2025: 661.5, 2023: 569 }
  },
  {
    id: "38",
    name: "西安市第三十八中学",
    shortName: "38中",
    code: "010203",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 660.5, 2023: 555 }
  },
  {
    id: "46",
    name: "西安市第四十六中学",
    shortName: "46中",
    code: "010402",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "雁塔区",
    campus: "本部",
    tags: ["南郊", "公办"],
    targeted: true,
    lines: { 2025: 659.3 }
  },
  {
    id: "changqing2",
    name: "长庆二中",
    shortName: "长庆二中",
    code: "010529",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "未央区",
    campus: "本部",
    tags: ["城北", "公办"],
    targeted: true,
    lines: { 2025: 655.7 }
  },
  {
    id: "dongfang",
    name: "西安市东方中学",
    shortName: "东方中学",
    code: "010218",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 655.1 }
  },
  {
    id: "yuhang",
    name: "西安市宇航中学",
    shortName: "宇航中学",
    code: "010620",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "航天基地",
    campus: "本部",
    tags: ["航天", "公办"],
    targeted: true,
    lines: { 2025: 654.6, 2023: 565 }
  },
  {
    id: "53",
    name: "西安市第五十三中学",
    shortName: "53中",
    code: "010403",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "雁塔区",
    campus: "本部",
    tags: ["南郊", "公办"],
    targeted: true,
    lines: { 2025: 652.7 }
  },
  {
    id: "43",
    name: "西安市第四十三中学",
    shortName: "43中",
    code: "010206",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "新城区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 652 }
  },
  {
    id: "42",
    name: "西安市第四十二中学",
    shortName: "42中",
    code: "010305",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["城西", "公办"],
    targeted: true,
    lines: { 2025: 651.3, 2023: 585 }
  },
  {
    id: "xadian",
    name: "西安电子科技中学",
    shortName: "电子科技中学",
    code: "010413",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "雁塔区",
    campus: "本部",
    tags: ["民办"],
    targeted: true,
    lines: { 2025: 649.1, 2024: 611, 2023: 629 }
  },
  {
    id: "xigang",
    name: "西安西港花园高级中学",
    shortName: "西港花园",
    code: "010621",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "灞桥区",
    campus: "本部",
    tags: ["民办"],
    targeted: true,
    lines: { 2025: 648.2 }
  },
  {
    id: "xiwai",
    name: "西安外国语学校",
    shortName: "西外附中",
    code: "010318",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "莲湖区",
    campus: "本部",
    tags: ["外语", "民办"],
    targeted: true,
    lines: { 2025: 647.1, 2023: 585 }
  },
  {
    id: "19",
    name: "西安市第十九中学",
    shortName: "19中",
    code: "010601",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "灞桥区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 644.1 }
  },
  {
    id: "62",
    name: "西安市第六十二中学",
    shortName: "62中",
    code: "010604",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "灞桥区",
    campus: "本部",
    tags: ["城东", "公办"],
    targeted: true,
    lines: { 2025: 641.9 }
  },
  {
    id: "25",
    name: "西安市第二十五中学",
    shortName: "25中",
    code: "010304",
    batch: "第二批次",
    level: "省标准",
    ownership: "公办",
    district: "莲湖区",
    campus: "本部",
    tags: ["城西", "公办"],
    targeted: true,
    lines: { 2025: 639.3, 2023: 559 }
  },
  {
    id: "bodi",
    name: "西安博迪学校",
    shortName: "博迪学校",
    code: "010425",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "雁塔区",
    campus: "本部",
    tags: ["民办"],
    targeted: true,
    lines: { 2025: 631 }
  },
  {
    id: "boai",
    name: "西安博爱学校",
    shortName: "博爱学校",
    code: "010521",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "未央区",
    campus: "本部",
    tags: ["民办"],
    targeted: true,
    lines: { 2025: 628.2 }
  },
  {
    id: "jinghua",
    name: "西咸泾河泾华学校",
    shortName: "泾华学校",
    code: "010544",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "西咸新区",
    campus: "泾河",
    tags: ["民办", "新区"],
    targeted: true,
    lines: { 2025: 627 }
  },
  {
    id: "siyuan",
    name: "西安思源中学",
    shortName: "思源中学",
    code: "010133",
    batch: "第二批次",
    level: "省标准",
    ownership: "民办",
    district: "灞桥区",
    campus: "本部",
    tags: ["民办"],
    targeted: true,
    lines: { 2025: 623.2 }
  },
  {
    id: "gx5",
    name: "西安高新区第五高级中学",
    shortName: "高新五高",
    code: "011008",
    batch: "第二批次",
    level: "普通",
    ownership: "公办",
    district: "高新区",
    campus: "本部",
    tags: ["高新", "公办"],
    targeted: false,
    lines: { 2025: 617.2, 2023: 577 }
  }
];
